### ISSUE TITLE
Latest version not published to NPM

### ISSUE THREAD

**Issue by jhalvorson** [onfido/api-javascript-client#10]
The latest available version on NPM is 1.0.1: https://www.npmjs.com/package/onfido, however, the current version on GitHub is 1.5.0.

I'm getting around this just now by installing via `yarn add onfido/api-javascript-client`.

**Comment by davetayls** [comment]
The version on npm doesn't look like it is being maintained by onfido.

Using the recommended install path of the git repository is really bad, the major version bump has broken our code without warning because it just pulls the latest from master.

Please can you setup an org on npm and publish legit, versioned packages? It would really help.

Thanks

**Comment by ciaran16** [comment]
Hi @jhalvorson, the latest version is now on npm.

Hi @davetayls, sorry about that, I wasn't aware installing from GitHub would automatically install breaking changes. I've added a couple of older versions (1.5.0, 1.6.0) to npm as well, hopefully you can use those and fix your code.

I've updated the README and will publish a patch version tomorrow so it's updated on npm. In the future, newer versions will be published to npm automatically.
